services:
  heimdall:
    extends:
      file: /opt/stacks/heimdall/compose.yml
      service: heimdall
    networks:
      - homelab
  pihole:
    extends:
      file: /opt/stacks/pihole/compose.yml
      service: pihole
  
  stirling-pdf:
    extends: 
      file: /opt/stacks/stirling-pdf/compose.yml
      service: stirling-pdf
    networks:
      - homelab
  
  caddy:
    extends:
      file: /opt/stacks/caddy/compose.yml
      service: caddy 
    networks:
      - homelab
  
  mealie:
    extends:
      file: /opt/stacks/mealie/compose.yml
      service: mealie
    networks:
      - homelab

  code:
    extends:
      file: /opt/stacks/code/compose.yml
      service: code-server
    networks:
      - homelab
  
  photoprism:
    extends:
      file: /opt/stacks/photoprism/compose.yml
      service: photoprism
    networks:
      - homelab

  homeassistant: 
    extends: 
      file: /opt/stacks/homeassistant/compose.yml
      service: homeassistant
    networks:
      - homelab

networks:
  homelab:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  mealie_data: