services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.5.1
    container_name: mealie
    restart: always
    ports:
      - 9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie_data:/app/data
    environment:
      ALLOW_SIGNUP: "true"
      PUID: "1000"
      PGID: "1000"
      TZ: "America/Anchorage"
      MAX_WORKERS: "1"
      WEB_CONCURRENCY: "1"

networks:
  homelab:
    external: true

volumes:
  mealie_data:
