version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    env_file:
      - /opt/stacks/pihole/.env
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: ${PIHOLE_ADMIN_PASSWORD}
      WEB_PORT: 8080
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped


