version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      #- TS_AUTH_KEY=${TAILSCALE_AUTHKEY}
      - TS_ROUTES=192.168.178.0/24
    volumes:
      - /dev/net/tun:/dev/net/tun
      - tailscale-state:/var/lib/tailscale
    network_mode: "host"
    restart: unless-stopped

volumes:
  tailscale-state: