apiVersion: v1
kind: Namespace
metadata:
  name: pdf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf
  namespace: pdf
spec:
  selector:
    matchLabels:
      app: pdf
  template:
    metadata:
      labels:
        app: pdf 
    spec:
      containers:
      - name: pdf
        image: frooodle/s-pdf:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /configs
        - name: tessdata
          mountPath: /usr/share/tessdata
      volumes:
        - name: tessdata
          hostPath:
            path: /var/pool/docker/stirling
            type: Directory
        - name: config
          hostPath:
            path: /var/pool/docker/stirling
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: pdf
  namespace: pdf
spec:
  selector:
    app: pdf
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf-ingress
  namespace: pdf
  labels:
    name: pdf
spec:
  rules:
  - host: pdf.home.box
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: pdf
            port: 
              number: 8080
